name: Scalafmt lint

on:
  pull_request:
    paths:
      - 'src/main/scala/**'
      - 'src/test/scala/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: stringbean/scalafmt-action@v1
        with:
          compare-branch: main
          version: 2.7.5