name: Scalafmt lint

on:
  pull_request:
    paths:
      - 'src/main/scala/**'
      - 'src/test/scala/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout branches
        run: |
          git remote set-branches origin main "${{github.head_ref}}"
          git fetch --depth 1
          git checkout "${{github.head_ref}}"

      - uses: stringbean/scalafmt-action@v2-dev
        with:
          compare-branch: origin/main
